### ISSUE TITLE
What is that `http` command in script file

### ISSUE THREAD

**Issue by marc-bouvier** [michelgrootjans/dot-game#10]
Hi @michelgrootjans. 

I try to run the `/scripts/simple_scenario.sh`, but **I cannot figure what is the `http` CLI tool** used in this script.

As a result I get `http: not found`

**Comment by michelgrootjans** [comment]
Hey Marc. It's a tool called httpie. If you feel a more generic tool can be used, feel free to update the script.

**Comment by marc-bouvier** [comment]
Wow! What a quick answer. Thanks a lot.
Works like a charm ! 

<img width="1359" alt="image" src="https://github.com/michelgrootjans/dot-game/assets/15436007/776b17cc-cff7-47b4-8830-80dffacc5380">
